In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [4]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,0.964799,-0.066449,0.986768,-0.358079,0.997266,1.181890,-1.615679,-1.210161,-0.628077,1.227274
1,-0.916511,-0.566395,-1.008614,0.831617,-1.176962,1.820544,1.752375,-0.984534,0.363896,0.209470
2,-0.109484,-0.432774,-0.457649,0.793818,-0.268646,-1.836360,1.239086,-0.246383,-1.058145,-0.297376
3,1.750412,2.023606,1.688159,0.006800,-1.607661,0.184741,-2.619427,-0.357445,-1.473127,-0.190039
4,-0.224726,-0.711303,-0.220778,0.117124,1.536061,0.597538,0.348645,-0.939156,0.175915,0.236224
...,...,...,...,...,...,...,...,...,...,...
995,-1.367638,1.462255,-1.154918,-0.290454,-0.413424,0.032396,1.545490,1.428760,1.687092,1.072542
996,-1.514876,-3.221016,-1.300744,0.395599,-0.527994,1.353069,1.777506,-1.680870,1.798510,0.034272
997,1.674633,1.754933,1.586154,0.018402,-1.514470,0.321593,-2.417694,0.692723,-1.503850,0.225264
998,-0.778609,-0.835689,-0.194842,1.097220,0.180071,-0.272933,-0.533188,-0.497354,2.472138,0.867187
999,0.248454,-1.003439,0.360460,-0.331352,1.389764,-1.345210,-0.740875,0.773240,0.185734,1.416412

In [5]:
pd.DataFrame(y)

     0
0    0
1    1
2    1
3    0
4    1
..  ..
995  1
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
logistic=LogisticRegression()

In [9]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [10]:
y_pred=logistic.predict(X_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]

In [11]:
logistic.predict_proba(X_test)

array([[7.74477909e-01, 2.25522091e-01],
       [3.36684957e-02, 9.66331504e-01],
       [6.70682154e-01, 3.29317846e-01],
       [7.98668032e-02, 9.20133197e-01],
       [9.76616650e-01, 2.33833501e-02],
       [4.13572804e-02, 9.58642720e-01],
       [9.79028767e-01, 2.09712329e-02],
       [9.59367261e-01, 4.06327393e-02],
       [8.08520049e-01, 1.91479951e-01],
       [6.84954318e-01, 3.15045682e-01],
       [9.13669448e-01, 8.63305524e-02],
       [2.63597018e-01, 7.36402982e-01],
       [5.25844192e-01, 4.74155808e-01],
       [2.11912354e-01, 7.88087646e-01],
       [7.93592056e-01, 2.06407944e-01],
       [9.46621678e-01, 5.33783219e-02],
       [2.62957933e-02, 9.73704207e-01],
       [3.24212617e-01, 6.75787383e-01],
       [3.14803584e-01, 6.85196416e-01],
       [2.04956217e-01, 7.95043783e-01],
       [5.04587065e-01, 4.95412935e-01],
       [9.66703630e-01, 3.32963696e-02],
       [2.00514796e-01, 7.99485204e-01],
       [7.77891908e-01, 2.22108092e-01],
       [8.72986315e-01, 1.27013685e-01],
       [4.01990726e-02, 9.59800927e-01],
       [9.21218522e-01, 7.87814776e-02],
       [8.14302359e-01, 1.85697641e-01],
       [4.84323961e-01, 5.15676039e-01],
       [3.45979014e-01, 6.54020986e-01],
       [6.82517287e-02, 9.31748271e-01],
       [5.40154632e-04, 9.99459845e-01],
       [9.69329756e-01, 3.06702442e-02],
       [9.72909425e-01, 2.70905746e-02],
       [9.42369499e-01, 5.76305006e-02],
       [5.19300818e-01, 4.80699182e-01],
       [8.46478994e-02, 9.15352101e-01],
       [3.25968944e-01, 6.74031056e-01],
       [4.76883185e-01, 5.23116815e-01],
       [1.53788412e-04, 9.99846212e-01],
       [9.15879079e-01, 8.41209206e-02],
       [8.64908414e-02, 9.13509159e-01],
       [4.79528887e-01, 5.20471113e-01],
       [9.35681383e-01, 6.43186173e-02],
       [9.77892918e-01, 2.21070816e-02],
       [5.85645655e-01, 4.14354345e-01],
       [1.57842356e-02, 9.84215764e-01],
       [7.62135212e-02, 9.23786479e-01],
       [1.34855065e-02, 9.86514493e-01],
       [5.30445112e-02, 9.46955489e-01],
       [8.06446503e-01, 1.93553497e-01],
       [4.80600460e-03, 9.95193995e-01],
       [5.04847224e-01, 4.95152776e-01],
       [8.68420588e-01, 1.31579412e-01],
       [8.92652368e-03, 9.91073476e-01],
       [5.92487141e-01, 4.07512859e-01],
       [1.57430997e-01, 8.42569003e-01],
       [9.76375749e-01, 2.36242514e-02],
       [9.85861892e-02, 9.01413811e-01],
       [9.04177979e-01, 9.58220211e-02],
       [6.72480581e-03, 9.93275194e-01],
       [6.94837167e-01, 3.05162833e-01],
       [7.57553517e-01, 2.42446483e-01],
       [3.10057665e-02, 9.68994234e-01],
       [3.06669056e-01, 6.93330944e-01],
       [1.74765000e-01, 8.25235000e-01],
       [8.36522765e-01, 1.63477235e-01],
       [8.97499950e-01, 1.02500050e-01],
       [3.36207606e-01, 6.63792394e-01],
       [1.63589641e-01, 8.36410359e-01],
       [3.22758711e-01, 6.77241289e-01],
       [4.48390227e-02, 9.55160977e-01],
       [2.14643172e-04, 9.99785357e-01],
       [9.68626181e-01, 3.13738187e-02],
       [1.85275122e-01, 8.14724878e-01],
       [8.76090291e-01, 1.23909709e-01],
       [9.74552911e-01, 2.54470888e-02],
       [1.69192536e-03, 9.98308075e-01],
       [9.42494179e-01, 5.75058208e-02],
       [1.66988763e-01, 8.33011237e-01],
       [7.93678282e-01, 2.06321718e-01],
       [9.40836049e-01, 5.91639514e-02],
       [1.01610448e-01, 8.98389552e-01],
       [8.74075354e-01, 1.25924646e-01],
       [2.28534077e-04, 9.99771466e-01],
       [8.78526575e-01, 1.21473425e-01],
       [8.44941860e-01, 1.55058140e-01],
       [8.53358212e-01, 1.46641788e-01],
       [8.69056654e-01, 1.30943346e-01],
       [1.28582007e-01, 8.71417993e-01],
       [2.73397191e-03, 9.97266028e-01],
       [2.14400967e-02, 9.78559903e-01],
       [1.08228331e-01, 8.91771669e-01],
       [2.63727024e-01, 7.36272976e-01],
       [5.77997736e-02, 9.42200226e-01],
       [2.16038259e-01, 7.83961741e-01],
       [9.32819141e-01, 6.71808586e-02],
       [9.41557701e-01, 5.84422990e-02],
       [4.08768304e-01, 5.91231696e-01],
       [9.17168952e-01, 8.28310478e-02],
       [4.74767472e-03, 9.95252325e-01],
       [9.38736508e-01, 6.12634915e-02],
       [1.56652749e-02, 9.84334725e-01],
       [9.97834411e-01, 2.16558917e-03],
       [9.91498786e-01, 8.50121430e-03],
       [2.95803470e-01, 7.04196530e-01],
       [9.79657844e-01, 2.03421564e-02],
       [4.24492959e-03, 9.95755070e-01],
       [4.46627026e-01, 5.53372974e-01],
       [1.04693540e-01, 8.95306460e-01],
       [1.74855153e-01, 8.25144847e-01],
       [6.03209371e-02, 9.39679063e-01],
       [6.56148601e-02, 9.34385140e-01],
       [1.19933445e-01, 8.80066555e-01],
       [8.58104363e-03, 9.91418956e-01],
       [8.59876891e-01, 1.40123109e-01],
       [6.84717395e-01, 3.15282605e-01],
       [1.95234632e-01, 8.04765368e-01],
       [9.82841776e-01, 1.71582240e-02],
       [9.47844801e-01, 5.21551992e-02],
       [6.97641026e-04, 9.99302359e-01],
       [3.92553985e-02, 9.60744601e-01],
       [9.40310910e-01, 5.96890899e-02],
       [2.89272173e-02, 9.71072783e-01],
       [5.42272369e-02, 9.45772763e-01],
       [1.63539867e-01, 8.36460133e-01],
       [2.30256645e-03, 9.97697434e-01],
       [1.31058827e-01, 8.68941173e-01],
       [7.18464282e-02, 9.28153572e-01],
       [5.19747785e-03, 9.94802522e-01],
       [1.66743033e-01, 8.33256967e-01],
       [8.64722657e-01, 1.35277343e-01],
       [2.03828936e-01, 7.96171064e-01],
       [3.85192279e-02, 9.61480772e-01],
       [4.25737942e-01, 5.74262058e-01],
       [1.22169118e-01, 8.77830882e-01],
       [9.69781847e-01, 3.02181531e-02],
       [8.44232927e-01, 1.55767073e-01],
       [9.51011404e-01, 4.89885962e-02],
       [3.65231656e-02, 9.63476834e-01],
       [2.97233519e-01, 7.02766481e-01],
       [9.83930559e-01, 1.60694414e-02],
       [8.50482377e-01, 1.49517623e-01],
       [9.69227146e-01, 3.07728545e-02],
       [5.70768072e-01, 4.29231928e-01],
       [6.08967868e-01, 3.91032132e-01],
       [1.52018704e-03, 9.98479813e-01],
       [9.05744695e-01, 9.42553048e-02],
       [9.84757221e-01, 1.52427790e-02],
       [9.88122823e-01, 1.18771771e-02],
       [2.69225535e-02, 9.73077447e-01],
       [9.93780846e-01, 6.21915371e-03],
       [9.23251233e-01, 7.67487674e-02],
       [4.95989754e-01, 5.04010246e-01],
       [9.29589501e-01, 7.04104985e-02],
       [9.83112237e-01, 1.68877626e-02],
       [3.74683662e-03, 9.96253163e-01],
       [9.41062433e-01, 5.89375673e-02],
       [4.83198636e-01, 5.16801364e-01],
       [1.28935351e-01, 8.71064649e-01],
       [9.66520562e-01, 3.34794385e-02],
       [9.51188169e-02, 9.04881183e-01],
       [8.98677581e-01, 1.01322419e-01],
       [9.34911237e-01, 6.50887635e-02],
       [8.83531964e-01, 1.16468036e-01],
       [7.75763221e-01, 2.24236779e-01],
       [8.74341863e-01, 1.25658137e-01],
       [8.47570117e-01, 1.52429883e-01],
       [9.62574483e-01, 3.74255167e-02],
       [2.72313989e-01, 7.27686011e-01],
       [1.02516135e-01, 8.97483865e-01],
       [5.00234285e-01, 4.99765715e-01],
       [8.54019577e-01, 1.45980423e-01],
       [9.18039310e-01, 8.19606897e-02],
       [1.42416420e-01, 8.57583580e-01],
       [5.78337026e-02, 9.42166297e-01],
       [8.08102236e-01, 1.91897764e-01],
       [5.20460632e-01, 4.79539368e-01],
       [1.34058715e-01, 8.65941285e-01],
       [9.08184651e-02, 9.09181535e-01],
       [8.49719108e-03, 9.91502809e-01],
       [2.60309646e-01, 7.39690354e-01],
       [5.84141579e-02, 9.41585842e-01],
       [3.63798304e-02, 9.63620170e-01],
       [1.19264420e-01, 8.80735580e-01],
       [7.89885122e-01, 2.10114878e-01],
       [8.43222920e-01, 1.56777080e-01],
       [9.98692380e-01, 1.30761976e-03],
       [8.78874611e-01, 1.21125389e-01],
       [3.56772596e-02, 9.64322740e-01],
       [6.03050103e-01, 3.96949897e-01],
       [9.86431515e-01, 1.35684853e-02],
       [7.93146504e-01, 2.06853496e-01],
       [8.47467088e-01, 1.52532912e-01],
       [1.13676130e-01, 8.86323870e-01],
       [8.19139947e-01, 1.80860053e-01],
       [8.96156182e-01, 1.03843818e-01],
       [9.08710566e-02, 9.09128943e-01],
       [1.34428958e-02, 9.86557104e-01],
       [6.36408287e-03, 9.93635917e-01],
       [8.98000692e-01, 1.01999308e-01],
       [1.42696817e-02, 9.85730318e-01],
       [6.47047414e-01, 3.52952586e-01],
       [6.45803708e-01, 3.54196292e-01],
       [8.98928926e-01, 1.01071074e-01],
       [3.98241682e-01, 6.01758318e-01],
       [4.78051531e-02, 9.52194847e-01],
       [1.25475872e-01, 8.74524128e-01],
       [4.58967728e-04, 9.99541032e-01],
       [1.81797283e-01, 8.18202717e-01],
       [9.76613797e-01, 2.33862032e-02],
       [9.05272249e-01, 9.47277509e-02],
       [7.81829796e-01, 2.18170204e-01],
       [9.35073716e-01, 6.49262838e-02],
       [9.77100484e-01, 2.28995160e-02],
       [4.05110751e-01, 5.94889249e-01],
       [9.51057021e-01, 4.89429794e-02],
       [1.38470656e-03, 9.98615293e-01],
       [8.12430453e-01, 1.87569547e-01],
       [2.25585075e-01, 7.74414925e-01],
       [2.36371049e-01, 7.63628951e-01],
       [8.08299504e-01, 1.91700496e-01],
       [9.36603714e-01, 6.33962865e-02],
       [1.88738512e-02, 9.81126149e-01],
       [1.77463037e-01, 8.22536963e-01],
       [2.46424378e-02, 9.75357562e-01],
       [8.70661557e-01, 1.29338443e-01],
       [9.63067534e-04, 9.99036932e-01],
       [8.29856023e-02, 9.17014398e-01],
       [9.78392538e-01, 2.16074617e-02],
       [9.69095061e-01, 3.09049389e-02],
       [7.81409729e-01, 2.18590271e-01],
       [9.96733261e-01, 3.26673858e-03],
       [9.57757229e-01, 4.22427714e-02],
       [8.04243134e-01, 1.95756866e-01],
       [9.61517017e-01, 3.84829830e-02],
       [9.97874704e-01, 2.12529648e-03],
       [9.24711398e-01, 7.52886020e-02],
       [2.42338405e-02, 9.75766160e-01],
       [1.35488530e-01, 8.64511470e-01],
       [9.93125832e-01, 6.87416827e-03],
       [3.44935605e-03, 9.96550644e-01],
       [7.44660946e-01, 2.55339054e-01],
       [1.36443551e-01, 8.63556449e-01],
       [2.40974492e-02, 9.75902551e-01],
       [8.43420401e-01, 1.56579599e-01],
       [1.45786514e-04, 9.99854213e-01],
       [9.40088052e-01, 5.99119484e-02],
       [1.05122328e-02, 9.89487767e-01],
       [7.86963112e-01, 2.13036888e-01],
       [7.24006621e-02, 9.27599338e-01],
       [4.59899501e-01, 5.40100499e-01],
       [4.78127589e-01, 5.21872411e-01],
       [9.84777169e-01, 1.52228310e-02],
       [9.27074807e-01, 7.29251934e-02],
       [6.48923088e-03, 9.93510769e-01],
       [5.64510633e-02, 9.43548937e-01],
       [3.32902371e-02, 9.66709763e-01],
       [2.84420293e-03, 9.97155797e-01],
       [9.84840147e-01, 1.51598529e-02],
       [2.32767092e-01, 7.67232908e-01],
       [5.81285578e-01, 4.18714422e-01],
       [6.14511717e-02, 9.38548828e-01],
       [2.20625875e-02, 9.77937413e-01],
       [9.97792594e-01, 2.20740624e-03],
       [9.69144758e-01, 3.08552418e-02],
       [6.10729149e-01, 3.89270851e-01],
       [4.52003638e-03, 9.95479964e-01],
       [5.22476985e-03, 9.94775230e-01],
       [8.38892074e-01, 1.61107926e-01],
       [2.94088160e-02, 9.70591184e-01],
       [2.44811806e-02, 9.75518819e-01],
       [5.04717788e-01, 4.95282212e-01],
       [9.96970998e-01, 3.02900221e-03],
       [4.38357935e-01, 5.61642065e-01],
       [7.55533719e-01, 2.44466281e-01],
       [7.21767578e-01, 2.78232422e-01],
       [9.15377123e-01, 8.46228773e-02],
       [9.55609414e-01, 4.43905856e-02],
       [1.49458769e-01, 8.50541231e-01],
       [4.73409989e-01, 5.26590011e-01],
       [8.82433027e-01, 1.17566973e-01],
       [1.02705527e-02, 9.89729447e-01],
       [9.86046455e-01, 1.39535451e-02],
       [1.41031062e-01, 8.58968938e-01],
       [1.44353766e-01, 8.55646234e-01],
       [4.31374884e-04, 9.99568625e-01],
       [8.21147498e-01, 1.78852502e-01],
       [9.60790250e-01, 3.92097505e-02],
       [7.05603626e-03, 9.92943964e-01],
       [8.69523194e-01, 1.30476806e-01],
       [4.76289789e-02, 9.52371021e-01],
       [3.64451357e-01, 6.35548643e-01],
       [7.16396395e-01, 2.83603605e-01],
       [4.75930773e-01, 5.24069227e-01],
       [2.76513494e-01, 7.23486506e-01],
       [1.77143904e-01, 8.22856096e-01],
       [3.87694387e-01, 6.12305613e-01],
       [8.73586021e-02, 9.12641398e-01],
       [8.74641664e-01, 1.25358336e-01]])

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [13]:
score=accuracy_score(y_test,y_pred)
print(score)

0.8466666666666667

In [14]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[118  17]
 [ 29 136]]

In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

#Hyperparamter tuning and Cross validation

In [16]:
def performGridSearch(model,m_type):
    from sklearn.model_selection import GridSearchCV,StratifiedKFold
    l1_ratio=[0,1,0.5]
    c_values=[100,10,1.0,0.1,0.01]
    solver=['newton-cg', 'newton-cholesky', 'sag', 'saga']
    if(m_type==1):
        params=dict(estimator__l1_ratio=l1_ratio,estimator__C=c_values,estimator__solver=solver)
        grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=3)
    else:
        params=dict(l1_ratio=l1_ratio,C=c_values,solver=solver)
        grid=GridSearchCV(estimator=model,param_grid=params,scoring='f1',cv=3)
    return grid

In [17]:
# GridsearchCV

In [18]:
model2=LogisticRegression()
grid2=performGridSearch(model2,0)
grid2.fit(X_train,y_train)

C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
90 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.85885998 0.85885998 0.85885998 0.85885998        nan        nan
        nan 0.85885998        nan        nan        nan 0.85885998
 0.85885998 0.85885998 0.85885998 0.85885998        nan        nan
        nan 0.86056828        nan        nan        nan 0.85885998
 0.86015455 0.86015455 0.86015455 0.86015455        nan        nan
        nan 0.86146079        nan        nan        nan 0.86146079
 0.8623579  0.8623579  0.8623579  0.8623579         nan        nan
        nan 0.86702214        nan        nan        nan 0.8665623
 0.8600966  0.8600966  0.8600966  0.8600966         nan        nan
        nan 0.85434315        nan        nan        nan 0.85478813]
  warnings.warn(

GridSearchCV(cv=3, estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'l1_ratio': [0, 1, 0.5],
                         'solver': ['newton-cg', 'newton-cholesky', 'sag',
                                    'saga']},
             scoring='f1')

In [19]:
grid2.best_params_,grid2.best_score_

({'C': 0.1, 'l1_ratio': 1, 'solver': 'saga'}, np.float64(0.8670221429127808))

In [20]:
y_pred=grid2.predict(X_test)

In [21]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

[[121  14]
 [ 30 135]]
              precision    recall  f1-score   support

           0       0.80      0.90      0.85       135
           1       0.91      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300

In [25]:
from sklearn.model_selection import RandomizedSearchCV
l1_ratio=[0,1,0.5]
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'newton-cholesky', 'sag', 'saga']
params=dict(l1_ratio=l1_ratio,C=c_values,solver=solver)
randomcv=RandomizedSearchCV(estimator=model2,param_distributions=params,cv=5,scoring='accuracy')

In [26]:
randomcv.fit(X_train,y_train)

C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
10 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.87       0.87       0.87       0.87       0.87       0.87285714
 0.87714286        nan        nan 0.87285714]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'l1_ratio': [0, 1, 0.5],
                                        'solver': ['newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [27]:
randomcv.best_score_

np.float64(0.8771428571428572)

In [28]:
randomcv.best_estimator_

LogisticRegression(C=0.01, l1_ratio=0, solver='newton-cholesky')

In [29]:
y_pred_random=randomcv.predict(X_test)

In [30]:
print(classification_report(y_test,y_pred_random))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300

In [31]:
Xm,ym=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [32]:
Xm

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]], shape=(1000, 10))

In [33]:
ym

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 2, 0, 2,
       2, 1, 1, 0, 2, 2, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 0, 2,
       1, 0, 1, 1, 1, 0, 2, 0, 2, 1, 0, 0, 0, 2, 0, 1, 2, 0, 1, 1, 0, 2,
       1, 1, 1, 0, 2, 0, 0, 0, 2, 0, 1, 1, 2, 2, 2, 2, 0, 2, 0, 2, 1, 2,
       2, 1, 1, 2, 0, 2, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 2, 0, 2, 2, 0,
       1, 2, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 2, 2, 0, 1, 2, 2, 0, 1, 2, 2,
       0, 2, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 1, 2, 0, 1, 1, 2, 2, 1, 1, 1,
       0, 0, 2, 1, 0, 1, 1, 2, 0, 1, 0, 2, 2, 1, 1, 0, 2, 1, 2, 1, 0, 0,
       0, 1, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2,
       1, 1, 0, 2, 1, 2, 1, 0, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 2, 0, 1, 1,
       0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 2, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 1, 0,
       1, 2, 1, 2, 1, 1, 2, 1, 2, 0, 0, 1, 0, 1, 2, 1, 1, 2, 2, 1, 2, 0,
       1, 2, 0, 2, 0, 2, 1, 2, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 1, 1,
       1, 1, 2, 1, 0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 2, 1, 2, 2, 0, 2, 1, 2, 2, 0,
       0, 2, 2, 2, 1, 2, 1, 2, 0, 1, 0, 2, 2, 2, 2, 0, 1, 2, 2, 1, 2, 1,
       2, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 2, 1, 0, 0, 0, 2, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 2, 1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 0, 2, 2, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 2, 2, 1, 1,
       1, 2, 2, 0, 0, 2, 2, 1, 2, 0, 0, 1, 1, 2, 0, 0, 2, 0, 1, 2, 1, 0,
       1, 0, 1, 0, 2, 2, 0, 2, 0, 2, 1, 0, 2, 1, 2, 1, 1, 2, 0, 2, 0, 1,
       2, 2, 0, 1, 0, 1, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 1, 2, 0, 1, 1, 0,
       0, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 2,
       0, 1, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1,
       0, 1, 0, 1, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 2, 2, 2, 1, 1, 0, 1, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 2, 2, 1,
       0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 1, 2, 1, 2, 0, 0,
       0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0,
       1, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 2, 2,
       1, 1, 1, 1, 2, 0, 1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 2, 1, 1, 2, 1, 0,
       1, 0, 1, 2, 0, 2, 1, 1, 1, 1])

In [44]:
Xm_train,Xm_test,ym_train,ym_test=train_test_split(Xm,ym,test_size=0.3,random_state=15)
np.unique(Xm)

array([-4.65996041, -4.4960885 , -4.42837367, ...,  3.9697546 ,
        4.60702631,  4.65588719], shape=(10000,))

In [35]:
from sklearn.multiclass import OneVsRestClassifier
logistic_m=OneVsRestClassifier(LogisticRegression())
logistic_m.fit(Xm_train,ym_train)
ym_pred=logistic_m.predict(Xm_test)

In [36]:
print(classification_report(ym_test,ym_pred))

              precision    recall  f1-score   support

           0       0.65      0.72      0.68       101
           1       0.52      0.38      0.44        95
           2       0.76      0.87      0.81       104

    accuracy                           0.66       300
   macro avg       0.64      0.66      0.64       300
weighted avg       0.65      0.66      0.65       300

In [37]:
cm=confusion_matrix(ym_test,ym_pred)
cm

array([[73, 23,  5],
       [36, 36, 23],
       [ 4, 10, 90]])

In [38]:
grid3=performGridSearch(logistic_m,1)
grid3.fit(Xm_train,ym_train)

C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
90 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 376, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 96, in _fit_binary
    estimator.fit(X, y, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 376, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 96, in _fit_binary
    estimator.fit(X, y, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 376, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 96, in _fit_binary
    estimator.fit(X, y, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 376, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 96, in _fit_binary
    estimator.fit(X, y, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 376, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\multiclass.py", line 96, in _fit_binary
    estimator.fit(X, y, **fit_params)
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lohchs\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GridSearchCV(cv=3,
             estimator=OneVsRestClassifier(estimator=LogisticRegression()),
             param_grid={'estimator__C': [100, 10, 1.0, 0.1, 0.01],
                         'estimator__l1_ratio': [0, 1, 0.5],
                         'estimator__solver': ['newton-cg', 'newton-cholesky',
                                               'sag', 'saga']},
             scoring='accuracy')

In [39]:
ym_pred3_prob=grid3.predict_proba(Xm_test)

In [40]:
ym_pred3_pos=ym_pred3_prob[:,1]
ym_pred3=(ym_pred3_pos >= 0.5).astype(int)
confusion_matrix(ym_test,ym_pred3)

array([[ 95,   6,   0],
       [ 75,  20,   0],
       [104,   0,   0]])

In [41]:
print(classification_report(ym_test,ym_pred))

              precision    recall  f1-score   support

           0       0.65      0.72      0.68       101
           1       0.52      0.38      0.44        95
           2       0.76      0.87      0.81       104

    accuracy                           0.66       300
   macro avg       0.64      0.66      0.64       300
weighted avg       0.65      0.66      0.65       300

In [42]:
print(grid3.best_score_,grid3.best_params_)

0.6299658853306922 {'estimator__C': 0.1, 'estimator__l1_ratio': 1, 'estimator__solver': 'saga'}

In [46]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def log_loss(y_true, y_pred, eps=1e-15):
    y_pred = np.clip(y_pred, eps, 1 - eps) # avoid log(0)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Example data
X = np.array([0.2, 0.4, 0.6])
y = np.array([0, 1, 1])
theta = 0.5

# Predictions
z = X * theta
y_pred = sigmoid(z)

print("Predicted Probabilities:", y_pred)
print("Log Loss:", log_loss(y, y_pred))

Predicted Probabilities: [0.52497919 0.549834   0.57444252]
Log Loss: 0.6322969246412299